group:
  repos: |
    UWM-YDSA/UWM-YDSA.github.io@main
  files:
    - source: admin/
      dest: admin/
    - src/_data/chapters.json
    - src/_includes/
    - src/404.md
    - static/
    - .eleventy.js
    - .gitignore
    - .nojekyll
    - LICENSE
    - package-lock.json
    - package.json
