group:
  - files:
      - admin/
      - src/_data/chapters.json
      - src/_includes/
      - src/404.md
      - static/
      - .eleventy.js
      - .gitignore
      - .nojekyll
      - LICENSE
      - package-lock.json
      - package.json
    repos: |
      UWM-YDSA/UWM-YDSA.github.io@main
